language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: arvitaly@list.ru
  api_key:
    secure: MH9O6GIPx0qezcQeHwMzxQ4QGCAlBmzQhojFBNeE8pjKBhEyS3LriJIZ7eszqSY9c/raq6nvKIRnrGyJzHs4vmzrECO/hBWkgRL6Zb2tR4XGeMwO3nWaZ+l3jw/uzoBHpv7JS3qeGTFq5l4NMYXG85U4t5VxtxyyBQmfJKhuPAeqvSBeWD57LP70Lz054NyRmRlYxmABBNUh3Qu0bykx/R/8bUmMiny3GvPc+lq1X5dojYVsqXBkEUE7l6tJabVOenfhAmoYvbAugoLjx9NGFtN7qWVwy0xKFbg4BGOWqDPGjMpIM7k+wWQ4pcKJj/P3yWxdNMKI+D1/bwI1LbKbLr+y32CLFEQoEOHaWvTqGMvya0GkxlGCQR3S40pfFh6H+BPzn4k26l1EjD853derd9ICTdOrsOucq+WafuGnfr8up4oW2Q4G/MRaQ05kEDOJjejqFQdcbfbnVEeMvy91GEsYLAzMzwXG4IMvtKx6EQ427EIDO0YaS6qxNJDI5RuDKUcC5cXYlY4cbi0tUcwIlLm3M+Ns2OXPT2qKLalOKXpyeS0gVd5lX10fkbb4usVdG/jO2inG88XUPtU4lvZU8fJ1dYDqhnJB7IKhB6kSGDomrzKwyvCyVHo/mYqf2yPtWb5wp55YD0ZY6Sj8mU/f1Z0RQh4ihBdwbx7kDpSiy3U=
